# Generated by Django 5.2.3 on 2025-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_identity_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='back_side_identity_card_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='front_side_identity_card_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='selfie_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
