# Generated by Django 5.2.3 on 2025-07-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_back_side_identity_card_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='back_side_identity_card',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='front_side_identity_card',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='selfie_photo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='back_side_identity_card_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='front_side_identity_card_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selfie_photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
