# Generated by Django 5.2.3 on 2025-07-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_back_side_identity_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='back_side_identity_card',
            field=models.ImageField(blank=True, null=True, upload_to='identity_cards/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='front_side_identity_card',
            field=models.ImageField(blank=True, null=True, upload_to='identity_cards/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='selfie_photo',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/'),
        ),
    ]
