# Generated by Django 5.2.3 on 2025-07-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_back_side_identity_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='back_side_identity_card',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='front_side_identity_card',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='selfie_photo',
        ),
    ]
