# Generated by Django 5.2.3 on 2025-08-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_app_version_profile_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='request_id',
            field=models.CharField(blank=True, help_text='Stores external API request ID', max_length=100, null=True),
        ),
    ]
