# Generated by Django 5.2.3 on 2025-09-05 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_otp_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiditVerificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('session_number', models.IntegerField(blank=True, null=True)),
                ('session_token', models.CharField(blank=True, max_length=100)),
                ('vendor_data', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(default='Not Started', max_length=50)),
                ('workflow_id', models.CharField(blank=True, max_length=100)),
                ('callback_url', models.URLField(blank=True)),
                ('verification_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
