# Generated by Django 5.2.3 on 2025-09-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_diditverificationsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_identity_verified',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('kyc_expired', 'KYC Expired'), ('in_review', 'In Review'), ('expired', 'Expired'), ('abandoned', 'Abandoned'), ('not_started', 'Not Started')], default='pending', max_length=20),
        ),
    ]
