# Generated by Django 5.2.3 on 2025-09-09 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_legacy_fields'),
        ('users', '0012_alter_customuser_is_identity_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='listings.locationdata'),
        ),
    ]
