version: '3.8'

services:
  web:
    build: .
    restart: always
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data: 