services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: velro_db
      POSTGRES_USER: velro_db_user
      POSTGRES_PASSWORD: BNS2rE5kaRnSoVKeS4MskdsYCg9Bs9T2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6380:6379"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

# uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload
