services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: p2pkilosales
      POSTGRES_USER: p2pkilosales
      POSTGRES_PASSWORD: p2pkilosales
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6380:6379"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:

# uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload
