services:
  - type: web
    name: p2pkilosales-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py create_superuser &&
        python manage.py collectstatic --noinput --clear &&
        uvicorn config.asgi:application --host 0.0.0.0 --port 8000
      "
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: adrash
      #     property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://p2pkilosales-backend.onrender.com
      - key: REDIS_URL
        fromService:
          type: redis
          name: p2pkilosales-redis
          property: connectionString
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_VERIFY_SERVICE
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: APPLE_BUNDLE_ID
        sync: false
      - key: APPLE_TEAM_ID
        sync: false
      - key: APPLE_KEY_ID
        sync: false
      - key: APPLE_PRIVATE_KEY
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DJANGO_SUPERUSER_PHONE
        sync: false

services:
  - type: redis
    name: p2pkilosales-redis
    plan: free 
