# Generated by Django 5.2.3 on 2025-06-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_country', models.CharField(max_length=100)),
                ('pickup_region', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('destination_region', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('travel_time', models.TimeField()),
                ('mode_of_transport', models.CharField(max_length=50)),
                ('maximum_weight_in_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_document', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_phone', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_tablet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_pc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_file', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
