# Generated by Django 5.2.3 on 2025-06-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travellisting',
            name='is_active',
        ),
        migrations.AddField(
            model_name='travellisting',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('published', 'Published'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='published', max_length=20),
        ),
    ]
