# Generated by Django 5.2.3 on 2025-06-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
