# Generated by Django 5.2.3 on 2025-06-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_country_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='destination_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_alerts', to='listings.country'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='destination_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_alerts', to='listings.region'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='pickup_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_alerts', to='listings.country'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='pickup_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_alerts', to='listings.region'),
        ),
    ]
