# Generated by Django 5.2.3 on 2025-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_alert_destination_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='travel_date',
            new_name='from_travel_date',
        ),
        migrations.AddField(
            model_name='alert',
            name='notify_for_any_destination_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='notify_for_any_pickup_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='notify_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='to_travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
