# Generated by Django 5.2.3 on 2025-06-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_travellisting_destination_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerequest',
            name='package_type',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('SMALL_PARCEL', 'Small Parcel'), ('MEDIUM_PARCEL', 'Medium Parcel'), ('LARGE_PARCEL', 'Large Parcel'), ('FRAGILE_ITEM', 'Fragile Item'), ('PERISHABLE_ITEM', 'Perishable Item'), ('MEDICINE', 'Medicine/Pharmaceutical'), ('VALUABLE_ITEM', 'Valuable Item'), ('OTHER', 'Other (Specify in description)')], default='DOCUMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='pickup_address',
            field=models.TextField(default='Addis Ababa, Bole airport'),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='receiver_address',
            field=models.TextField(default='Bahir Dar, belay zeleke building'),
        ),
        migrations.AddField(
            model_name='packagerequest',
            name='receiver_phone_number',
            field=models.CharField(default='251956434529', max_length=20),
            preserve_default=False,
        ),
    ]
