# Generated by Django 5.2.3 on 2025-06-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellisting',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('published', 'Published'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('fully-booked', 'Fully Booked')], default='published', max_length=20),
        ),
    ]
