# Generated by Django 5.2.3 on 2025-06-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_packagerequest_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagerequest',
            name='package_type',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('SMALL_PARCEL', 'Small Parcel'), ('MEDIUM_PARCEL', 'Medium Parcel'), ('LARGE_PARCEL', 'Large Parcel'), ('FRAGILE_ITEM', 'Fragile Item'), ('PERISHABLE_ITEM', 'Perishable Item'), ('MEDICINE', 'Medicine/Pharmaceutical'), ('VALUABLE_ITEM', 'Valuable Item'), ('OTHER', 'Other (Specify in description)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='packagerequest',
            name='pickup_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='packagerequest',
            name='receiver_address',
            field=models.TextField(),
        ),
    ]
