# Generated by Django 5.2.3 on 2025-09-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_travellisting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='travellisting',
            name='fullSuitcaseOnly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='travellisting',
            name='destination_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_listings', to='listings.country'),
        ),
        migrations.AlterField(
            model_name='travellisting',
            name='destination_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_listings', to='listings.region'),
        ),
        migrations.AlterField(
            model_name='travellisting',
            name='pickup_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_listings', to='listings.country'),
        ),
        migrations.AlterField(
            model_name='travellisting',
            name='pickup_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_listings', to='listings.region'),
        ),
        migrations.AlterField(
            model_name='travellisting',
            name='price_per_document',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Location Data',
                'unique_together': {('name', 'country', 'country_code')},
            },
        ),
        migrations.AddField(
            model_name='travellisting',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_listings', to='listings.locationdata'),
        ),
        migrations.AddField(
            model_name='travellisting',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_listings', to='listings.locationdata'),
        ),
    ]
