# Generated by Django 5.2.3 on 2025-09-09 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_travellisting_fullsuitcaseonly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_alerts', to='listings.locationdata'),
        ),
        migrations.AddField(
            model_name='alert',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_alerts', to='listings.locationdata'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='destination_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_alerts', to='listings.country'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='destination_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_alerts', to='listings.region'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='pickup_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_alerts', to='listings.country'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='pickup_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_alerts', to='listings.region'),
        ),
    ]
