# Generated by Django 5.2.3 on 2025-09-09 07:24

from django.db import migrations


def convert_alert_locations(apps, schema_editor):
    """
    Convert existing alert records from Country/Region model to LocationData model
    """
    Alert = apps.get_model('listings', 'Alert')
    LocationData = apps.get_model('listings', 'LocationData')
    
    # Process all existing alerts
    for alert in Alert.objects.all():
        # Skip if already converted
        if alert.pickup_location and alert.destination_location:
            continue
            
        # Convert pickup location if needed
        if alert.pickup_country and not alert.pickup_location:
            country_name = alert.pickup_country.name
            country_code = alert.pickup_country.code[:2]  # Using first 2 chars of code
            city_name = alert.pickup_region.name if alert.pickup_region else country_name
            
            # Create or get LocationData for pickup
            pickup_location, _ = LocationData.objects.get_or_create(
                name=city_name,
                country=country_name,
                country_code=country_code
            )
            alert.pickup_location = pickup_location
        
        # Convert destination location if needed
        if alert.destination_country and not alert.destination_location:
            country_name = alert.destination_country.name
            country_code = alert.destination_country.code[:2]  # Using first 2 chars of code
            city_name = alert.destination_region.name if alert.destination_region else country_name
            
            # Create or get LocationData for destination
            destination_location, _ = LocationData.objects.get_or_create(
                name=city_name,
                country=country_name,
                country_code=country_code
            )
            alert.destination_location = destination_location
            
        # Save the updated alert
        alert.save()


def reverse_convert_alert_locations(apps, schema_editor):
    """
    This is a no-op since we want to keep the data in the new format even if we roll back
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alert_destination_location_alert_pickup_location_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_alert_locations, reverse_convert_alert_locations),
    ]
