# Generated by Django 5.2.3 on 2025-09-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_convert_alert_locations'),
    ]

    operations = [
        # First make non-nullable
        migrations.RunSQL(
            # Forward SQL - make fields not null
            """
            UPDATE listings_alert SET 
                pickup_location_id = (SELECT MIN(id) FROM listings_locationdata) 
            WHERE pickup_location_id IS NULL;
            
            UPDATE listings_alert SET 
                destination_location_id = (SELECT MIN(id) FROM listings_locationdata) 
            WHERE destination_location_id IS NULL;
            
            ALTER TABLE listings_alert ALTER COLUMN pickup_location_id SET NOT NULL;
            ALTER TABLE listings_alert ALTER COLUMN destination_location_id SET NOT NULL;
            """,
            # Reverse SQL - make fields nullable again
            """
            ALTER TABLE listings_alert ALTER COLUMN pickup_location_id DROP NOT NULL;
            ALTER TABLE listings_alert ALTER COLUMN destination_location_id DROP NOT NULL;
            """
        ),
        
        # Remove legacy fields
        migrations.RemoveField(
            model_name='alert',
            name='pickup_country',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='pickup_region',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='destination_country',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='destination_region',
        ),
    ]
