# Generated by Django 5.2.3 on 2025-09-16 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_legacy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellisting',
            name='mode_of_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='listings.transporttype'),
        ),
    ]
