# Generated by Django 5.2.3 on 2025-09-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_travellisting_mode_of_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travellisting',
            name='mode_of_transport',
        ),
    ]
