# Generated by Django 5.2.3 on 2025-06-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
    ]
