# Generated by Django 5.2.3 on 2025-07-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
